### ISSUE TITLE
Search box for oData entitities to add

### ISSUE THREAD

**Issue by UM001** [OData/ODataConnectedService#158]
ERP systems have large oData files. For development only a few entities are required.
Searching for the right data entity can be improved with a search box on top of the selection.
Additionally, adding all related tables should be selectable as a lot of related tables are added which are not required.

**Comment by habbes** [comment]
Hi @UM001, thanks for the suggestion. What do you mean by "Adding all related tables should be selectable as a lot of related tables are added which are not required". Are you referring to the fact that when you select an entity, other related entities are selected automatically as well?

**Comment by UM001** [comment]
Two things:
For instance I want only the customers table, then I need to scroll down a lot;
Once I select customers table, then it automatically selects all related tables like invoices etc.
I get now a very large file of MB's and Visual Studio crashes on this file (60MB large).
In this case I only want to create a sales order with some sales lines and lookup a customer and if products in the sales line exists. A JSON would also do, but I do not see how to output that so I can make simpler classes.

**Comment by UM001** [comment]
VS2019 keeps on crashing and closes and gives IO error.

**Comment by habbes** [comment]
@UM001 When you select an entity, e.g. Customer, then OData Connected Service also selects types that Customer references. This includes types that are used in Customer's properties, or the type that Customer inherits from. If the types referenced by Customer are not selected, then the code that is generated would not compile because Customer class would reference types that are not defined.

v0.11 improves the type selection and allows more granularity for un-selecting bound operations. Maybe this could help your situation. It also fixes some bugs in the type selection page. But that version has not yet been published.

Are you generating a single file or multiple files? If the generated code is in a single large file, then you could also opt to generate multiple files in the advanced settings. This will split the generated classes in different files and might be more VS-friendly. You can try that as a temporary workaround.

**Comment by UM001** [comment]
Thank you. I indeed generate multiple files now. I understand the references to other entities. Not all references are needed to insert a sales order or sales line.

**Comment by habbes** [comment]
@UM001 Welcome. I assume that means it's working on. You can try again when v0.11 is published and see if the improvements to the selection page help.
In addition, if it's possible to share the metadata, we can take a look to see whether there are any references between the entities you want to select, and those that get auto-selected by OData Connected Service.

**Comment by UM001** [comment]
Unfortunately, I cannot share the url in public.

**Comment by unchase** [comment]
> Unfortunately, I cannot share the url in public.

Hi, @UM001 
Can you share a not sensitive part of metadata (not url)?
