### ISSUE TITLE
Support for Metadata annotations

### ISSUE THREAD

**Issue by KamyarP** [OData/ODataConnectedService#167]
The OData Connected Service code generator ignores metadata annotations (e.g description for a property/entity is always "there are no comments for {property/entity} in schema" although provided metadata file contains annotation of term Org.OData.Core.V1.Description)

I have chosen OData Connected Service client code generator to connect to Microsoft Dynamics CRM 9 using Customer Engagement API. The API supports providing additional information using [Metadata annotations](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-types-operations#metadata-annotations) which can make the generated code far more understandable for developers.

P.S. if there's any documentation regarding the structure of the project or some guidelines, I'd love to contribute.

**Comment by marabooy** [comment]
@KamyarP Glad to see you are willing to send a contribution to this. The repository is structured so that the changes you need to add if they are for code generation these will need to go the the ODataT4CodeGenerator.tt file in the Templates directory which then generates the CSfile used in connected service. Any Ui changes will need to go to the Views if this is going to be an option that users can use while generating the code.

**Comment by KamyarP** [comment]
@marabooy Thanks for the hint. I have already started working on supporting `Descrpition` annotation and will create PR soon as it's done.

**Comment by unchase** [comment]
Was the PR #168 resolved this issue?
