### ISSUE TITLE
Casing incorrect when generating off Microsoft Dataverse metadata

### ISSUE THREAD

**Issue by devkeydet** [OData/ODataConnectedService#198]
### Describe the bug
When using the attached metadata, which is metadata generated from Microsoft Dataverse:
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/overview
...I get errors:
![connected-service-gen-errors](https://user-images.githubusercontent.com/4499296/107977343-f0bbb180-6f88-11eb-96d9-ddf17c564905.png)
[ODataV4Metadata.zip](https://github.com/OData/ODataConnectedService/files/5983163/ODataV4Metadata.zip)

#### Version of the Project affected
ODataConnectedService v0.11.1
VisualStudio Version v16.8.5
Microsoft.Odata.Client v7.8.1

#### To Reproduce
See this tweet: 
https://twitter.com/devkeydet/status/1361361234768109574

#### Expected behavior
Proper casing is generated so code compiles without find/replace workaround

#### Actual behavior
Generated code won't compile due to casing generation.

#### Screenshots
See tweet.

#### Additional context
See tweet.

**Comment by habbes** [comment]
Hi @devkeydet, I looked at the metadata file that you shared and noticed that both the relationattribute and serviceplan are defined as entity types with all lower-case names, i.e. `relationshipattribute` and `serviceplan`, as you can see in the screenshots below:

![image](https://user-images.githubusercontent.com/8460169/108322434-826c2e80-71d6-11eb-8ad6-f34a38fabcda.png)
![image](https://user-images.githubusercontent.com/8460169/108322489-92840e00-71d6-11eb-890d-868c1ebcc85f.png)

When generating the service, if you disable the option to generate C#-style names (i.e. PascalCase names) in the Advanced Settings page, then classes will be generated with the same names as the ones in the metadata, i.e. `relationshipattrbute` and `serviceplan` as you can see in the screenshots below:
![image](https://user-images.githubusercontent.com/8460169/108323917-4c2fae80-71d8-11eb-9e67-1a907a0421cc.png)
![image](https://user-images.githubusercontent.com/8460169/108323967-5ea9e800-71d8-11eb-9f1f-ea7c82f3814a.png)


If you enable the C#-style casing option, then generated name will be `Relationshipattribute`:
![image](https://user-images.githubusercontent.com/8460169/108324287-c06a5200-71d8-11eb-8c89-cdc4afcb0227.png)
![image](https://user-images.githubusercontent.com/8460169/108324403-ec85d300-71d8-11eb-8834-e388ddf10517.png)

Therefore it seems that the code being generated is correct given the names defined in your metadata.

**Comment by habbes** [comment]
Actually, upon closer inspection of your metadata, it seems that you define an entity type name `relationshipattribute` and a complex type named `RelationshipAttribute`:

![image](https://user-images.githubusercontent.com/8460169/108324753-5900d200-71d9-11eb-90d4-8a0734b66974.png)
![image](https://user-images.githubusercontent.com/8460169/108324800-6ddd6580-71d9-11eb-9616-15c74ff9914d.png)

And the connected service generates two distinct classes: `relationshipattribute` and `RelationshipAttribute`. I'd be curious to see a snippet of your client code to see which class you're referencing.

But the entity type can only be generated as `relationshipattribute` or `Relationshipattribute` depending on how you set the C#-style casing option. This is the expected behaviour, not a bug.

**Comment by devkeydet** [comment]
Makes sense.  Either way, if I set casing or not, I have to manually update my generated code.  Sounds like the root cause is the metadata. @JimDaly is tracking this issue too.  I'll make sure he is aware.  Thanks for the investigation!
