### ISSUE TITLE
odata-cli tracking option is missing

### ISSUE THREAD

**Issue by artur-moreira** [OData/ODataConnectedService#269]
As per #247

--no-tracking |-n - disables entity and property tracking

Should assume that UseDataServiceCollection would be true, but never assigned or supported on CLI commands, so defaults to false producing a proxy without change tracking enabled

**Comment by andreas-developer** [comment]
Any progress on this issue? We're using the D365 F&O OData interface and the CLI is the only option that doesn't require a machine with 40+ Gb RAM when generating the client. But without the tracking we're losing a lot of functionality in our existing integrations.

**Comment by bradschoen** [comment]
We too prefer the CLI for multiple reasons and cannot use it because of this issue.

**Comment by ElizabethOkerio** [comment]
@bradschoen @andreas-developer we'll check on this as soon as possible.

**Comment by suomimar-low** [comment]
Will there be a fix for this? I see the PR is almost ready?

**Comment by suomimar-low** [comment]
We are using OData with Business Central and for that use Odata CLI for automatic proxy class generation in CI. But we cannot use this client generator now because we cannot do any updates via data context because property tracking is disabled. All Business Central entities contain such properties that are read only. We would need to do manual property tracking which would not make sense in this context - if that would work either.

**Comment by batetech** [comment]
I ran into this same issue when working on a .NET project that is using Dynamics 365 data entities which needs upgraded to use VS2019/VS2022 instead of VS2017.  Since PR #330 has been stuck for 2 months because it is out-of-date with the base branch, I went ahead and implemented this as a new PR #339 which adds a new option --use-data-service-collection (-dsc) to add the entity/property tracking.  The up-side of adding the new option this way (instead of as --no-tracking) is that it will not break or change the default for anyone that is already using odata-cli to generate their code, but will give others the option to opt in to the property tracking when needed.  Hopefully this can get reviewed and included at some point in the future. 

@ElizabethOkerio this is my first PR on a public project, so please let me know if there is anything I missed.

**Comment by marcmognol** [comment]
Hi, you are right my PR should be rebased, but as I didn't get any feedback for it, it looked like this project don't accept any new PR.

Please tell me if I have to rebase it, and if this project is still alive.

Thanks

**Comment by suomimar-low** [comment]
Hi! I think it might be good to rebase? Next time they have to review the PR, it would contain up-to-date code. For us this PR is a must so thanks for doing this. 👍

**Comment by marcmognol** [comment]
Hi @suomimar-low I've rebased my branch.

**Comment by marcmognol** [comment]
Hi @suomimar-low I've rebased my branch again :) Hope this PR will be merged soon.
