### ISSUE TITLE
The extension module is not loaded when debugging in the VS experimental instance

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#29]
Hello.

I would like to contribute to the development of the project, but I can not do this for the reason stated in the FAQ:

> **Question**: The extension module is not loaded when debugging in the Visual Studio experimental instance, or it is not listed as part of the "Add Connected Service" options

The proposed solution does not help:

> **Workaround**: Disable signing by going to the Project Properties> Signing and disabling both "Sign the assembly" and "Delay sign only" options.

Tried to do this in:
1) Visual Studio 2017 Community 2017 v15.9.19
2) Visual Studio 2017 Community 2019 v16.4.3

![vs2019](https://user-images.githubusercontent.com/29679226/76409137-08fd7680-639f-11ea-9fcc-c49f6d746ad0.png)

But the connected service is still not available in the list (for .NET Framework Class Library, .NET Framework Console App, .NET Standard Class Library, .NET Core Class Library and others):

![connectedServices](https://user-images.githubusercontent.com/29679226/76409272-364a2480-639f-11ea-82d4-6a38f2474b37.png)

Could you help me solve this issue?

**Comment by habbes** [comment]
Hi @unchase. thank you for you interest in contributing to the project.

Here's one way to solve the issue:
You need to disable signing on both the ODataConnectedService and ODataConnectedService.Tests projects. I recommend you open the ODataConnectedService.Tests.sln solution.

Then you will need to change the `AssemblyInfo.cs` in the OdataConnectedService project and remove the `PublicKey` from the `InternalVisibleTo` attribute on the last line, so that it just reads:
```c#
[assembly: InternalsVisibleTo("ODataConnectedService.Tests")]
```

Make sure not to commit these changes as part of your PR.

Alternatively you could disable strong name validation for the `Microsoft.OData.ConnectedService.dll` and `ODataConnectedService.Tests.dll` assemblies on your machine.

This is a bit annoying and we're working on improving the development process so that you won't need to do this.

**Comment by unchase** [comment]
I disabled signing on both the ODataConnectedService and ODataConnectedService.Tests projects:

![1](https://user-images.githubusercontent.com/29679226/76416060-68fa1a00-63ab-11ea-9123-7b10cbe4a7fa.png)
![2](https://user-images.githubusercontent.com/29679226/76416066-6c8da100-63ab-11ea-9ac8-0b814619c339.png)

I removed the PublicKey from the InternalVisibleTo attribute:

![3](https://user-images.githubusercontent.com/29679226/76416088-76170900-63ab-11ea-892e-05af0d26e0b8.png)

In addition, I followed the recommendations from the [documentation](https://docs.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature):
1) Create a DWORD entries to registry: *HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework and HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework keys.*
2) Use **sn.exe -Vr "<assembly_full_path>"** for both assemblies

But the issue was not solved.

**Comment by habbes** [comment]
@unchase it maybe that you already have the latest MS OData Connected Service installed on your VS instance. To check whether this is the issue, increase the version of the development OData Connected Service to something like 0.5.0 in the vsix manifest configuration and check whether it's able to load.

**Comment by unchase** [comment]
@habbes, thank you. It really helped me.
