### ISSUE TITLE
Metadata URL with values in Query String

### ISSUE THREAD

**Issue by victorperez2911** [OData/ODataConnectedService#48]
Hi.

The url to get the metadata from my OData API requires setting the Api version in a parameter sent in the url query string.

http://[host]:[port]/odata/$metadata **?api-version=1.0**

In this case, when you try to configure the connected service, an error occurs because the extension tries to concatenate "$metadata" to the end of the URL.

How can I use this feature with the exposed scenario?

Thank you

Victor Perez

![image](https://user-images.githubusercontent.com/11770654/76968550-dc4ddf80-6907-11ea-8b2f-5f7e93f9c798.png)

**Comment by unchase** [comment]
Hi, @victorperez2911 
For now you can download the metadata file and use it for client code generation.

**Comment by victorperez2911** [comment]
> Hi, @victorperez2911
> For now you can download the metadata file from URL and use it locally for client code generation.

Hello @unchase , thanks for the attention.

How do I do that?

**Comment by unchase** [comment]
> > Hi, @victorperez2911
> > For now you can download the metadata file from URL and use it locally for client code generation.
> 
> Hello @unchase , thanks for the attention.
> 
> How do I do that?

Open the URL in your browser (for example, _https://services.odata.org/TripPinRESTierService/(S(wjy3mzjhuafogibt4edls5li))/$metadata_). Save as xml-file. Set full path of saved metadata-file (for example, _D:\Downloads\metadata.xml_) in the TextBox on the first page of Connected Service wizard.

**Comment by habbes** [comment]
Thanks for reporting this @victorperez2911. It seems that we use a naive test with `string.EndsWith` to see if the last path of the URL is `$metadata` instead of parsing it: fixhttps://github.com/OData/ODataConnectedService/blob/bc35a78d48401c900d3d6d2c07b69281cc234a5d/src/ViewModels/ConfigODataEndpointViewModel.cs#L90

This should probably be a quick fix. If you are open to contributing a PR for this we will be happy to review it. Thanks.

**Comment by facundo91** [comment]
May I jump in to get the fix done? @habbes
