### ISSUE TITLE
oDataClient.cs too large to use

### ISSUE THREAD

**Issue by fbruemmer73** [OData/ODataConnectedService#57]
Hello,

I'm using the client generator to generate an odata client for D365FO. This used to work in the past. However, since D365FO is constantly evolving and growing, so does the number of data entities and the size of the metadata. I believe we have reached a point, where the generated client code is too large to be compiled by Visual Studio. The only way to make this work is to remove parts of the metadata manually. This however is very error-prone and takes forever.

It would be nice to be able to select a specific number of data entities for client code generation in a future release..

**Comment by KenitoInc** [comment]
@fbruemmer73 As Paul said, this issue has been fixed in OData connected service extension. Let me close this issue.

**Comment by bdbvb** [comment]
I'm on version 0.7.1. I'm using a large metadata file (from MS Dynamics CRM OData web api). When I configure the T4 template such that GenerateMultipleFiles = false, it generates it, but the file is so large (over a million lines) that Visual Studio sometimes crashes. When I set GenerateMultipleFiles = true, it only generates one file; that file is smaller, but doesn't compile because it apparently doesn't have any of the entity classes; the entity classes are not written out at all.

**Comment by paulodero** [comment]
> I'm on version 0.7.1. I'm using a large metadata file (from MS Dynamics CRM OData web api). When I configure the T4 template such that GenerateMultipleFiles = false, it generates it, but the file is so large (over a million lines) that Visual Studio sometimes crashes. When I set GenerateMultipleFiles = true, it only generates one file; that file is smaller, but doesn't compile because it apparently doesn't have any of the entity classes; the entity classes are not written out at all.

@bdbvb Thanks for reporting this. This is a known issue and is being worked on. In the meantime you can set generate multiple files checkbox  from the connected service UI. You should be able to generate multiple files.

**Comment by habbes** [comment]
@bdbvb in version 0.9.0 you can also choose which classes to include in the generated code. This allows you to remove the stuff you don't need and reduce the size of the generated code.
